<a href="https://colab.research.google.com/github/farhanasajeer/github/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,4,5,8])
a

array([1, 4, 5, 8])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a[:2]

array([1, 4])

In [ ]:
a[3]

8

In [ ]:
a[0]=5
a

array([5, 4, 5, 8])

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a[0][0]

1

In [ ]:
a[0,1]

2

slicing


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a[1,:]

array([4, 5, 6])

In [ ]:
a[:,2]

array([3, 6])

In [ ]:
a[-1:,-2:]

array([[5, 6]])

**shape**

In [ ]:
a.shape

(2, 3)

**datatype**

In [ ]:
a.dtype

dtype('int64')

length

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
len(a)

2

in stmnt

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
2 in a

True

In [ ]:
0 in a

False

**reshape**

In [ ]:
a=np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a=a.reshape((5,2))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
a.shape

(5, 2)

**COPY**

In [ ]:
a=np.array([1,2,3])
b=a
c=a.copy()
a[0]=0
a

array([0, 2, 3])

In [ ]:
b

array([0, 2, 3])

In [ ]:
c

array([1, 2, 3])

**TOLIST**

In [ ]:
a=np.array([1,2,3],float)
a.tolist()

[1.0, 2.0, 3.0]

In [ ]:
list(a)

[1.0, 2.0, 3.0]

to **String**

In [ ]:
from array import array
a =np.array([1,2,3])
s = a.tostring()
print(s)


b'\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00'


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
np.fromstring(s)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


array([4.9e-324, 9.9e-324, 1.5e-323])

In [ ]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
a.fill(0)
a

array([0, 0, 0])

In [ ]:
a=np.array(range(6)).reshape((2,3))
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a.transpose()


array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

basics + - / 

In [ ]:
a=np.array([1,2,3])
b=np.array([5,2,6])
a+b

array([6, 4, 9])

In [ ]:
a-b

array([-4,  0, -3])

In [ ]:
a*b

array([ 5,  4, 18])

In [ ]:
b/a

array([5., 1., 2.])

In [ ]:
a%b

array([1, 0, 3])

In [ ]:
b**a

array([  5,   4, 216])

ARAY ITERATION

In [ ]:
a=np.array([1,4,5],int)
for x in a:
  print(x)

1
4
5


In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
for x in a:
  print(x)

[1 2]
[3 4]
[5 6]


In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
for(x,y) in a:
  print(x*y)

2
12
30


BASIC OPERATIONS

In [ ]:
a=np.array([2,4,3])
a.sum()
print(x*y)

30


In [ ]:
a.prod()

24

In [ ]:
a=np.array([2,1,9])
a.mean()

4.0

In [ ]:
a.var()

12.666666666666666

In [ ]:
a.std()

3.559026084010437

In [ ]:
a=np.array([2,1,9])
a.min()

1

In [ ]:
a.max()

9

In [ ]:
a=np.array([2,1,9])
a.argmin()

1

In [ ]:
a=np.array([2,1,9])
a.argmax()

2

In [ ]:
a=np.array([[0,2],[3,-1],[3,5]])
a.mean(axis=0)

array([2., 2.])

In [ ]:
a.mean(axis=1)

array([1., 1., 4.])

In [ ]:
a.min(axis=1)

array([ 0, -1,  3])

In [ ]:
a.max(axis=0)

array([3, 5])