<a href="https://colab.research.google.com/github/farhanasajeer/github/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
a=np.array([1,4,5,8])
a

array([1, 4, 5, 8])

In [9]:
type(a)

numpy.ndarray

In [10]:
a[:2]

array([1, 4])

In [11]:
a[3]

8

In [12]:
a[0]=5
a

array([5, 4, 5, 8])

In [13]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a[0][0]

1

In [15]:
a[0,1]

2

slicing


In [16]:
a=np.array([[1,2,3],[4,5,6]])
a[1,:]

array([4, 5, 6])

In [17]:
a[:,2]

array([3, 6])

In [19]:
a[-1:,-2:]

array([[5, 6]])

**shape**

In [20]:
a.shape

(2, 3)

**datatype**

In [21]:
a.dtype

dtype('int64')

length

In [22]:
a=np.array([[1,2,3],[4,5,6]])
len(a)

2

in stmnt

In [25]:
a=np.array([[1,2,3],[4,5,6]])
2 in a

True

In [26]:
0 in a

False

**reshape**

In [27]:
a=np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a=a.reshape((5,2))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [30]:
a.shape

(5, 2)

**COPY**

In [32]:
a=np.array([1,2,3])
b=a
c=a.copy()
a[0]=0
a

array([0, 2, 3])

In [33]:
b

array([0, 2, 3])

In [34]:
c

array([1, 2, 3])

**TOLIST**

In [35]:
a=np.array([1,2,3],float)
a.tolist()

[1.0, 2.0, 3.0]

In [36]:
list(a)

[1.0, 2.0, 3.0]